const responses = [
  {
    id: 1,
    name: "Dana Osborn",
    response: "We got dinner recently at Sobre Masa and it was the BEST",
    user_id: 2,
    question_id: 1, 
  },
  {
    id: 2,
    name: "Geena Massara",
    response: "Ooh I think it would be fun to learn design",
    user_id: 3,
    question_id: 2,
  },
  {
    id: 3,
    name: "Andrea Larsen",
    response: "It's What's Inside was CRAZY I highly recommend",
    user_id: 4,
    question_id: 3,
  },
  {
    id: 4,
    name: "Jordan Phillips",
    response: "Going full nesting mode has been super creative. Really loving Baby B's nursery",
    user_id: 5,
    question_id: 4,
  },
  {
    id: 5,
    name: "Lauren Phillips",
    response: "March 14th I can FEEL IT",
    user_id: 1,
    question_id: 5,
  },
  {
    id: 6,
    name: "Geena Massara",
    response: "I know I'm late to the game but the Trader Joes pork soup dumplings are insane",
    user_id: 3,
    question_id: 1, 
  },
  {
    id: 7,
    name: "Jordan Phillips",
    response: "We're in peak winter citrus season so I made Alison Roman's salmon with citrus and her salad. Sooo good",
    user_id: 3,
    question_id: 1, 
  },
  {
    id: 8,
    name: "Andrea Larsen",
    response: "Definitely something in design but I could neverrrr go back to school",
    user_id: 4,
    question_id: 2,
  },
  {
    id: 9,
    name: "Lauren Phillips",
    response: "Severance is BACK babyyyy",
    user_id: 1,
    question_id: 3,
  },
  {
    id: 10,
    name: "Dana Osborn",
    response: "I rewatched Rent recently and I forgot how much I loved it!",
    user_id: 2,
    question_id: 3,
  },
  {
    id: 11,
    name: "Lauren Phillips",
    response: "I just finished making my soon to come nephew the CUTEST sweater who knew babies were so teeeeeeny",
    user_id: 1,
    question_id: 4,
  },
  {
    id: 12,
    name: "Dana Osborn",
    response: "March 3rd little pisces boy :)",
    user_id: 2,
    question_id: 5,
  },
  {
    id: 13,
    name: "Geena Massara",
    response: "Ooh I feel like he's going to come late. Maybe March 15th?",
    user_id: 3,
    question_id: 5,
  },
  {
    id: 14,
    name: "Andrea Larsen",
    response: "I think he's going to be a St Patricks Day baby!!",
    user_id: 4,
    question_id: 5,
  },
];

export default responses;
